---
# vars file for roles/node-exporter
node_exporter_user: node_exporter

node_exporter_dir_url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz

node_exporter_tmp_dir: /tmp/node_exporter-1.3.1.linux-amd64
node_exporter_usr_dir: /usr/local/bin/

node_exporter_svc: node_exporter
